export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const START_GET_EMPLOYEES = "START_GET_EMPLOYEES";
export const COMPLETE_GET_EMPLOYEES = "COMPLETE_GET_EMPLOYEES";

export const VOTE_EMPLOYEE = "VOTE_EMPLOYEE";